In [1]:
import os
from dotenv import load_dotenv
import pandas as pd
import numpy as np

load_dotenv()
TRAIN_SET = os.getenv("TRAIN_PATH")
TEST_SET  = os.getenv("TEST_PATH")

train = pd.read_csv(TRAIN_SET)
test = pd.read_csv(TEST_SET)

train = train.drop(['id'], axis=1)
test = test.drop(['id'], axis=1)

In [2]:
train.head()

,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,...,PCIAT-PCIAT_18,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
0,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,NaN,...,4.0,2.0,4.0,55.0,NaN,NaN,NaN,Fall,3.0,2.0
1,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,22.0,...,0.0,0.0,0.0,0.0,Fall,46.0,64.0,Summer,0.0,0.0
2,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,NaN,...,2.0,1.0,1.0,28.0,Fall,38.0,54.0,Summer,2.0,0.0
3,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,NaN,...,3.0,4.0,1.0,44.0,Summer,31.0,45.0,Winter,0.0,1.0
4,Spring,18,1,Summer,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
test.head()

,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,...,BIA-BIA_TBW,PAQ_A-Season,PAQ_A-PAQ_A_Total,PAQ_C-Season,PAQ_C-PAQ_C_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday
0,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,NaN,...,32.6909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall,3.0
1,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,22.0,...,27.0552,NaN,NaN,Fall,2.340,Fall,46.0,64.0,Summer,0.0
2,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,NaN,...,NaN,NaN,NaN,Summer,2.170,Fall,38.0,54.0,Summer,2.0
3,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,NaN,...,45.9966,NaN,NaN,Winter,2.451,Summer,31.0,45.0,Winter,0.0
4,Spring,18,1,Summer,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Summer,1.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
train = train.dropna(subset=['sii'])

y_train = train['sii']

y_train.shape

(2736,)

In [5]:
#i would like to collapse two features into one: Fitness_Endurance-Time_Mins and Fitness_Endurance-Time_Sec into one feature (the seconds one)
train['Fitness_Endurance-Time'] = train['Fitness_Endurance-Time_Sec'] + (train['Fitness_Endurance-Time_Mins']*60) + train['Fitness_Endurance-Max_Stage']
train = train.drop(['Fitness_Endurance-Time_Mins'], axis=1)
train = train.drop(['Fitness_Endurance-Time_Sec'], axis=1)
train = train.drop(['Fitness_Endurance-Max_Stage'], axis=1)
train.head()

,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,...,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii,Fitness_Endurance-Time
0,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,NaN,...,2.0,4.0,55.0,NaN,NaN,NaN,Fall,3.0,2.0,NaN
1,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,22.0,...,0.0,0.0,0.0,Fall,46.0,64.0,Summer,0.0,0.0,NaN
2,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,NaN,...,1.0,1.0,28.0,Fall,38.0,54.0,Summer,2.0,0.0,458.0
3,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,NaN,...,4.0,1.0,44.0,Summer,31.0,45.0,Winter,0.0,1.0,583.0
5,Spring,13,1,Winter,50.0,Summer,22.279952,59.5,112.2,NaN,...,2.0,1.0,34.0,Summer,40.0,56.0,Spring,0.0,1.0,NaN

In [6]:
# I want to collapse togheter all the features that have the substring 'FGC': 
# for each row I want to sumup in the FGC feature the values of it with the value of the 'FGC-Zone' specific feature
def clash_features(train):
    FGC_features = [col for col in train.columns if 'FGC' in col] 
    FGC_features.remove('FGC-Season')
    removed_features = 0
    zone_features_to_drop = []
    #train['Physical'] = train[physical_features].sum(axis=1)

    # I have FGC-FGC_CU, FGC-FGC_CU_Zone; FGC-GSND, FGC-GSND_Zone; and it goes on. I want to sum up in the FGC-FGC_CU a (+10% of that feature)*FGC_CU_Zone for every feature that has the corrispective _Zone feature   
    for feature in FGC_features:
        zone_feature = feature + '_Zone'

        if zone_feature in train.columns:
            print(f'Feature: {feature} - Zone: {zone_feature}')
            # Update the feature with 10% of the corresponding zone feature
            train[feature] = train[feature] + (train[zone_feature] * 0.1)
            # Add the zone_feature to the drop list
            zone_features_to_drop.append(zone_feature)
            removed_features += 1

    # Drop the zone features
    train = train.drop(zone_features_to_drop, axis=1)
    return train

In [7]:
train = clash_features(train)

Feature: FGC-FGC_CU - Zone: FGC-FGC_CU_Zone
Feature: FGC-FGC_GSND - Zone: FGC-FGC_GSND_Zone
Feature: FGC-FGC_GSD - Zone: FGC-FGC_GSD_Zone
Feature: FGC-FGC_PU - Zone: FGC-FGC_PU_Zone
Feature: FGC-FGC_SRL - Zone: FGC-FGC_SRL_Zone
Feature: FGC-FGC_SRR - Zone: FGC-FGC_SRR_Zone
Feature: FGC-FGC_TL - Zone: FGC-FGC_TL_Zone

In [8]:
train.head()

,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,...,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii,Fitness_Endurance-Time
0,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,NaN,...,2.0,4.0,55.0,NaN,NaN,NaN,Fall,3.0,2.0,NaN
1,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,22.0,...,0.0,0.0,0.0,Fall,46.0,64.0,Summer,0.0,0.0,NaN
2,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,NaN,...,1.0,1.0,28.0,Fall,38.0,54.0,Summer,2.0,0.0,458.0
3,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,NaN,...,4.0,1.0,44.0,Summer,31.0,45.0,Winter,0.0,1.0,583.0
5,Spring,13,1,Winter,50.0,Summer,22.279952,59.5,112.2,NaN,...,2.0,1.0,34.0,Summer,40.0,56.0,Spring,0.0,1.0,NaN

In [9]:
# i want to print all the features which are present only in train set
train_cols = set(train.columns)
test_cols = set(test.columns)
print(train_cols - test_cols)

{'PCIAT-PCIAT_19', 'PCIAT-PCIAT_15', 'PCIAT-PCIAT_07', 'PCIAT-PCIAT_Total', 'PCIAT-PCIAT_17', 'PCIAT-PCIAT_18', 'PCIAT-PCIAT_14', 'PCIAT-PCIAT_02', 'PCIAT-PCIAT_08', 'PCIAT-Season', 'sii', 'Fitness_Endurance-Time', 'PCIAT-PCIAT_05', 'PCIAT-PCIAT_06', 'PCIAT-PCIAT_04', 'PCIAT-PCIAT_11', 'PCIAT-PCIAT_13', 'PCIAT-PCIAT_12', 'PCIAT-PCIAT_01', 'PCIAT-PCIAT_16', 'PCIAT-PCIAT_10', 'PCIAT-PCIAT_09', 'PCIAT-PCIAT_03', 'PCIAT-PCIAT_20'}

In [10]:
# i want to drop all the non numerical features
X_train_num = train.select_dtypes(include=[np.number])

In [11]:
# i want to convert all the train columns to float
X_train_num = X_train_num.astype(float)

In [12]:
# i want to see the correlation between the only train features and the sii. Print that in a for loop
num_of_features = 0
correlation = X_train_num.corr()
correlation.sort_values(by='sii', ascending=False, inplace=True)
for col in X_train_num.columns:
    num_of_features += 1
    print(f"{col} : {correlation['sii'][col]}")

print("---------------------\n",f"Number of features: {num_of_features}")

Basic_Demos-Age : 0.3659904866603875
Basic_Demos-Sex : -0.10014836137814971
CGAS-CGAS_Score : -0.08526076127412004
Physical-BMI : 0.22112457970705188
Physical-Height : 0.37353007602305544
Physical-Weight : 0.3259380513287666
Physical-Waist_Circumference : 0.2728847687353721
Physical-Diastolic_BP : 0.050971149746987465
Physical-HeartRate : -0.024571709134461182
Physical-Systolic_BP : 0.1353358304209164
FGC-FGC_CU : 0.24514453885655624
FGC-FGC_GSND : 0.14943845325142732
FGC-FGC_GSD : 0.16013357236299144
FGC-FGC_PU : 0.1809429977926483
FGC-FGC_SRL : -0.04693375634421341
FGC-FGC_SRR : -0.03230663157250516
FGC-FGC_TL : 0.1067718186840289
BIA-BIA_Activity_Level_num : 0.06008515853600128
BIA-BIA_BMC : -0.010336136993440548
BIA-BIA_BMI : 0.22781784759890336
BIA-BIA_BMR : 0.0319654262597662
BIA-BIA_DEE : 0.045238527246931656
BIA-BIA_ECW : 0.03041443134665423
BIA-BIA_FFM : 0.031965369846319994
BIA-BIA_FFMI : 0.10270223892385262
BIA-BIA_FMI : 0.07705373336097672
BIA-BIA_Fat : 0.03735715143822173
BIA-BIA_Frame_num : 0.1659362470112953
BIA-BIA_ICW : 0.04665266448072986
BIA-BIA_LDM : 0.021695548256569275
BIA-BIA_LST : 0.0676028654031608
BIA-BIA_SMM : 0.046691985542252804
BIA-BIA_TBW : 0.03751253327999688
PAQ_A-PAQ_A_Total : -0.05038579943979693
PAQ_C-PAQ_C_Total : 0.005664881488280223
PCIAT-PCIAT_01 : 0.617882778257052
PCIAT-PCIAT_02 : 0.6945974581176867
PCIAT-PCIAT_03 : 0.694735858052695
PCIAT-PCIAT_04 : 0.5893417249981481
PCIAT-PCIAT_05 : 0.7227224790228133
PCIAT-PCIAT_06 : 0.6455955119502313
PCIAT-PCIAT_07 : 0.4608635925588827
PCIAT-PCIAT_08 : 0.6954577541938565
PCIAT-PCIAT_09 : 0.6604853586290386
PCIAT-PCIAT_10 : 0.6899716781588726
PCIAT-PCIAT_11 : 0.6099643043905082
PCIAT-PCIAT_12 : 0.37084371916637415
PCIAT-PCIAT_13 : 0.705679068402847
PCIAT-PCIAT_14 : 0.6759525652087088
PCIAT-PCIAT_15 : 0.7513993973053708
PCIAT-PCIAT_16 : 0.6985664918019463
PCIAT-PCIAT_17 : 0.7298671411254292
PCIAT-PCIAT_18 : 0.7311121314356369
PCIAT-PCIAT_19 : 0.6832929951844556
PCIAT-PCIAT_20 : 0.7030129206802043
PCIAT-PCIAT_Total : 0.899681248425972
SDS-SDS_Total_Raw : 0.2296921909720375
SDS-SDS_Total_T : 0.23298153659255016
PreInt_EduHx-computerinternet_hoursday : 0.33652553443492095
sii : 1.0
Fitness_Endurance-Time : -0.059679742639783
---------------------
 Number of features: 61

In [13]:
# i want to see the correlation between the only train features and the PCIAT. Print that in a for loop
num_of_features = 0
correlation = X_train_num.corr()
correlation.sort_values(by='PCIAT-PCIAT_Total', ascending=False, inplace=True)
for col in X_train_num.columns:
    num_of_features += 1
    print(f"{col} : {correlation['PCIAT-PCIAT_Total'][col]}")

print("---------------------\n",f"Number of features: {num_of_features}")

Basic_Demos-Age : 0.40955893004425936
Basic_Demos-Sex : -0.09364794987714749
CGAS-CGAS_Score : -0.07054209175506433
Physical-BMI : 0.24085815342882216
Physical-Height : 0.4207652971201519
Physical-Weight : 0.35304782208824853
Physical-Waist_Circumference : 0.32701304404603704
Physical-Diastolic_BP : 0.06932119160652951
Physical-HeartRate : -0.03759386630720302
Physical-Systolic_BP : 0.1470813158857649
FGC-FGC_CU : 0.2856041883941729
FGC-FGC_GSND : 0.14964315374175322
FGC-FGC_GSD : 0.15747958809488838
FGC-FGC_PU : 0.197503687980134
FGC-FGC_SRL : -0.08853105726178269
FGC-FGC_SRR : -0.07441650346019323
FGC-FGC_TL : 0.13262090266333668
BIA-BIA_Activity_Level_num : 0.08454812941125465
BIA-BIA_BMC : -0.008869864431638749
BIA-BIA_BMI : 0.248060080826345
BIA-BIA_BMR : 0.03700896316268028
BIA-BIA_DEE : 0.05309415134479328
BIA-BIA_ECW : 0.03556843242696345
BIA-BIA_FFM : 0.03700891365056593
BIA-BIA_FFMI : 0.10969353592476255
BIA-BIA_FMI : 0.08586259431049705
BIA-BIA_Fat : 0.03854812299920539
BIA-BIA_Frame_num : 0.193630997740564
BIA-BIA_ICW : 0.052593098042615125
BIA-BIA_LDM : 0.025885096892410222
BIA-BIA_LST : 0.0756231335304729
BIA-BIA_SMM : 0.05291243056889156
BIA-BIA_TBW : 0.04301500572103578
PAQ_A-PAQ_A_Total : -0.026853553435817492
PAQ_C-PAQ_C_Total : -0.021942931151556187
PCIAT-PCIAT_01 : 0.7279586274054309
PCIAT-PCIAT_02 : 0.7888024959524452
PCIAT-PCIAT_03 : 0.8233360306042623
PCIAT-PCIAT_04 : 0.6253938530979879
PCIAT-PCIAT_05 : 0.8309932302923771
PCIAT-PCIAT_06 : 0.7032613693641024
PCIAT-PCIAT_07 : 0.4917677248902384
PCIAT-PCIAT_08 : 0.7704992937712601
PCIAT-PCIAT_09 : 0.7209530747578442
PCIAT-PCIAT_10 : 0.7614628593102883
PCIAT-PCIAT_11 : 0.6847798741004689
PCIAT-PCIAT_12 : 0.4121939264539711
PCIAT-PCIAT_13 : 0.7719900970468018
PCIAT-PCIAT_14 : 0.7219951593134097
PCIAT-PCIAT_15 : 0.8239959883066746
PCIAT-PCIAT_16 : 0.769422373277713
PCIAT-PCIAT_17 : 0.8237084780906256
PCIAT-PCIAT_18 : 0.8020304477437746
PCIAT-PCIAT_19 : 0.7372432541029227
PCIAT-PCIAT_20 : 0.7542767494528174
PCIAT-PCIAT_Total : 1.0
SDS-SDS_Total_Raw : 0.23443180610412534
SDS-SDS_Total_T : 0.23771818767076733
PreInt_EduHx-computerinternet_hoursday : 0.37412437856504543
sii : 0.899681248425972
Fitness_Endurance-Time : -0.052091035373863406
---------------------
 Number of features: 61

In [14]:
feature_clusters = ['Physical', 'FGC', 'BIA', 'PCIAT-PCIAT_Total']

# i want to see the correlation between the feature of the dataset in which the name is in feature_clusters and the target
for cluster in feature_clusters:
    print('----------------')
    print(cluster)
    print('----------------')
    cluster_cols = [col for col in X_train_num.columns if cluster in col]
    print(X_train_num[cluster_cols].corrwith(X_train_num['sii']).sort_values(ascending=False))

----------------
Physical
----------------
Physical-Height                 0.373530
Physical-Weight                 0.325938
Physical-Waist_Circumference    0.272885
Physical-BMI                    0.221125
Physical-Systolic_BP            0.135336
Physical-Diastolic_BP           0.050971
Physical-HeartRate             -0.024572
dtype: float64
----------------
FGC
----------------
FGC-FGC_CU      0.245145
FGC-FGC_PU      0.180943
FGC-FGC_GSD     0.160134
FGC-FGC_GSND    0.149438
FGC-FGC_TL      0.106772
FGC-FGC_SRR    -0.032307
FGC-FGC_SRL    -0.046934
dtype: float64
----------------
BIA
----------------
BIA-BIA_BMI                   0.227818
BIA-BIA_Frame_num             0.165936
BIA-BIA_FFMI                  0.102702
BIA-BIA_FMI                   0.077054
BIA-BIA_LST                   0.067603
BIA-BIA_Activity_Level_num    0.060085
BIA-BIA_SMM                   0.046692
BIA-BIA_ICW                   0.046653
BIA-BIA_DEE                   0.045239
BIA-BIA_TBW                   0.037513
BIA-BIA_Fat                   0.037357
BIA-BIA_BMR                   0.031965
BIA-BIA_FFM                   0.031965
BIA-BIA_ECW                   0.030414
BIA-BIA_LDM                   0.021696
BIA-BIA_BMC                  -0.010336
dtype: float64
----------------
PCIAT-PCIAT_Total
----------------
PCIAT-PCIAT_Total    0.899681
dtype: float64

In [15]:
feature_clusters = ['Physical', 'FGC', 'BIA', 'PreInt_EduHx']

# i want to see the correlation between the feature of the dataset in which the name is in feature_clusters and the target
for cluster in feature_clusters:
    print('----------------')
    print(cluster)
    print('----------------')
    cluster_cols = [col for col in X_train_num.columns if cluster in col]
    print(X_train_num[cluster_cols].corrwith(X_train_num['PCIAT-PCIAT_Total']).sort_values(ascending=False))

----------------
Physical
----------------
Physical-Height                 0.420765
Physical-Weight                 0.353048
Physical-Waist_Circumference    0.327013
Physical-BMI                    0.240858
Physical-Systolic_BP            0.147081
Physical-Diastolic_BP           0.069321
Physical-HeartRate             -0.037594
dtype: float64
----------------
FGC
----------------
FGC-FGC_CU      0.285604
FGC-FGC_PU      0.197504
FGC-FGC_GSD     0.157480
FGC-FGC_GSND    0.149643
FGC-FGC_TL      0.132621
FGC-FGC_SRR    -0.074417
FGC-FGC_SRL    -0.088531
dtype: float64
----------------
BIA
----------------
BIA-BIA_BMI                   0.248060
BIA-BIA_Frame_num             0.193631
BIA-BIA_FFMI                  0.109694
BIA-BIA_FMI                   0.085863
BIA-BIA_Activity_Level_num    0.084548
BIA-BIA_LST                   0.075623
BIA-BIA_DEE                   0.053094
BIA-BIA_SMM                   0.052912
BIA-BIA_ICW                   0.052593
BIA-BIA_TBW                   0.043015
BIA-BIA_Fat                   0.038548
BIA-BIA_BMR                   0.037009
BIA-BIA_FFM                   0.037009
BIA-BIA_ECW                   0.035568
BIA-BIA_LDM                   0.025885
BIA-BIA_BMC                  -0.008870
dtype: float64
----------------
PreInt_EduHx
----------------
PreInt_EduHx-computerinternet_hoursday    0.374124
dtype: float64

In [16]:
train.head()

,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,...,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii,Fitness_Endurance-Time
0,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,NaN,...,2.0,4.0,55.0,NaN,NaN,NaN,Fall,3.0,2.0,NaN
1,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,22.0,...,0.0,0.0,0.0,Fall,46.0,64.0,Summer,0.0,0.0,NaN
2,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,NaN,...,1.0,1.0,28.0,Fall,38.0,54.0,Summer,2.0,0.0,458.0
3,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,NaN,...,4.0,1.0,44.0,Summer,31.0,45.0,Winter,0.0,1.0,583.0
5,Spring,13,1,Winter,50.0,Summer,22.279952,59.5,112.2,NaN,...,2.0,1.0,34.0,Summer,40.0,56.0,Spring,0.0,1.0,NaN

In [17]:
y_PCIAT = train['PCIAT-PCIAT_Total']

# i want to drop all the features in train which have the substring PCIAT
X_train = train.drop([col for col in train.columns if 'PCIAT' in col], axis=1).drop(['sii'], axis=1)
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2736 entries, 0 to 3958
Data columns (total 49 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Basic_Demos-Enroll_Season               2736 non-null   object
 1   Basic_Demos-Age                         2736 non-null   int64
 2   Basic_Demos-Sex                         2736 non-null   int64
 3   CGAS-Season                             2342 non-null   object
 4   CGAS-CGAS_Score                         2342 non-null   float64
 5   Physical-Season                         2595 non-null   object
 6   Physical-BMI                            2527 non-null   float64
 7   Physical-Height                         2530 non-null   float64
 8   Physical-Weight                         2572 non-null   float64
 9   Physical-Waist_Circumference            483 non-null    float64
 10  Physical-Diastolic_BP                   2478 non-null   float64
 11  Physical-HeartRate                      2486 non-null   float64
 12  Physical-Systolic_BP                    2478 non-null   float64
 13  Fitness_Endurance-Season                1260 non-null   object
 14  FGC-Season                              2647 non-null   object
 15  FGC-FGC_CU                              1884 non-null   float64
 16  FGC-FGC_GSND                            864 non-null    float64
 17  FGC-FGC_GSD                             864 non-null    float64
 18  FGC-FGC_PU                              1874 non-null   float64
 19  FGC-FGC_SRL                             1877 non-null   float64
 20  FGC-FGC_SRR                             1879 non-null   float64
 21  FGC-FGC_TL                              1885 non-null   float64
 22  BIA-Season                              1844 non-null   object
 23  BIA-BIA_Activity_Level_num              1813 non-null   float64
 24  BIA-BIA_BMC                             1813 non-null   float64
 25  BIA-BIA_BMI                             1813 non-null   float64
 26  BIA-BIA_BMR                             1813 non-null   float64
 27  BIA-BIA_DEE                             1813 non-null   float64
 28  BIA-BIA_ECW                             1813 non-null   float64
 29  BIA-BIA_FFM                             1813 non-null   float64
 30  BIA-BIA_FFMI                            1813 non-null   float64
 31  BIA-BIA_FMI                             1813 non-null   float64
 32  BIA-BIA_Fat                             1813 non-null   float64
 33  BIA-BIA_Frame_num                       1813 non-null   float64
 34  BIA-BIA_ICW                             1813 non-null   float64
 35  BIA-BIA_LDM                             1813 non-null   float64
 36  BIA-BIA_LST                             1813 non-null   float64
 37  BIA-BIA_SMM                             1813 non-null   float64
 38  BIA-BIA_TBW                             1813 non-null   float64
 39  PAQ_A-Season                            363 non-null    object
 40  PAQ_A-PAQ_A_Total                       363 non-null    float64
 41  PAQ_C-Season                            1440 non-null   object
 42  PAQ_C-PAQ_C_Total                       1440 non-null   float64
 43  SDS-Season                              2527 non-null   object
 44  SDS-SDS_Total_Raw                       2527 non-null   float64
 45  SDS-SDS_Total_T                         2525 non-null   float64
 46  PreInt_EduHx-Season                     2719 non-null   object
 47  PreInt_EduHx-computerinternet_hoursday  2654 non-null   float64
 48  Fitness_Endurance-Time                  727 non-null    float64
dtypes: float64(37), int64(2), object(10)
memory usage: 1.0+ MB

In [18]:
print("Features shape: ", X_train.shape, "\nTarget shape: ", y_PCIAT.shape)

Features shape:  (2736, 49)
Target shape:  (2736,)

In [19]:
def drop_columns(df, threshold):
    minimum_non_NaN = len(df) * threshold   
    dropped_columns = df.columns[df.isnull().sum() > (len(df) - minimum_non_NaN)].tolist()
    new_df = df.drop(columns=dropped_columns)

    return new_df, dropped_columns

X_train, dropped_columns = drop_columns(X_train, 0.3)

print("Dropped columns: ", dropped_columns)

Dropped columns:  ['Physical-Waist_Circumference', 'PAQ_A-Season', 'PAQ_A-PAQ_A_Total', 'Fitness_Endurance-Time']

In [20]:
X_train.head()

,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,Physical-Diastolic_BP,...,BIA-BIA_LST,BIA-BIA_SMM,BIA-BIA_TBW,PAQ_C-Season,PAQ_C-PAQ_C_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday
0,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,NaN,...,38.9177,19.5413,32.6909,NaN,NaN,NaN,NaN,NaN,Fall,3.0
1,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,75.0,...,39.4497,15.4107,27.0552,Fall,2.340,Fall,46.0,64.0,Summer,0.0
2,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,65.0,...,NaN,NaN,NaN,Summer,2.170,Fall,38.0,54.0,Summer,2.0
3,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,60.0,...,58.9338,26.4798,45.9966,Winter,2.451,Summer,31.0,45.0,Winter,0.0
5,Spring,13,1,Winter,50.0,Summer,22.279952,59.5,112.2,60.0,...,79.6982,35.3804,63.1265,Spring,4.110,Summer,40.0,56.0,Spring,0.0

## RESTART:

In [21]:
import os
from dotenv import load_dotenv
import pandas as pd
import numpy as np

load_dotenv()
TRAIN_SET = os.getenv("TRAIN_PATH")
TEST_SET  = os.getenv("TEST_PATH")
DESCRIPTION = os.getenv("DESCRIPTION_PATH")
    
train = pd.read_csv(TRAIN_SET)
test = pd.read_csv(TEST_SET)
description = pd.read_csv(DESCRIPTION)

train = train.drop(['id'], axis=1)
test = test.drop(['id'], axis=1)


train.head()

,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,...,PCIAT-PCIAT_18,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
0,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,NaN,...,4.0,2.0,4.0,55.0,NaN,NaN,NaN,Fall,3.0,2.0
1,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,22.0,...,0.0,0.0,0.0,0.0,Fall,46.0,64.0,Summer,0.0,0.0
2,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,NaN,...,2.0,1.0,1.0,28.0,Fall,38.0,54.0,Summer,2.0,0.0
3,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,NaN,...,3.0,4.0,1.0,44.0,Summer,31.0,45.0,Winter,0.0,1.0
4,Spring,18,1,Summer,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
train = train.dropna(subset=['sii'])
train = train.dropna(subset=['PCIAT-PCIAT_Total'])

y_train = train['PCIAT-PCIAT_Total']
y_train.shape

(2736,)

In [23]:
def intersect_features(train_set, test_set):
    smaller_train = train_set[train_set.columns.intersection(test_set.columns)]
    return smaller_train

X_train = intersect_features(train, test)
X_train.shape

(2736, 58)

In [24]:
X_train.head()

,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,...,BIA-BIA_TBW,PAQ_A-Season,PAQ_A-PAQ_A_Total,PAQ_C-Season,PAQ_C-PAQ_C_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday
0,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,NaN,...,32.6909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall,3.0
1,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,22.0,...,27.0552,NaN,NaN,Fall,2.340,Fall,46.0,64.0,Summer,0.0
2,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,NaN,...,NaN,NaN,NaN,Summer,2.170,Fall,38.0,54.0,Summer,2.0
3,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,NaN,...,45.9966,NaN,NaN,Winter,2.451,Summer,31.0,45.0,Winter,0.0
5,Spring,13,1,Winter,50.0,Summer,22.279952,59.5,112.2,NaN,...,63.1265,NaN,NaN,Spring,4.110,Summer,40.0,56.0,Spring,0.0

In [25]:
def drop_columns(df, threshold):
    minimum_non_NaN = len(df) * threshold   
    dropped_columns = df.columns[df.isnull().sum() > (len(df) - minimum_non_NaN)].tolist()
    new_df = df.drop(columns=dropped_columns)

    return new_df, dropped_columns

X_train, dropped_columns = drop_columns(X_train, 0.4)
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2736 entries, 0 to 3958
Data columns (total 48 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Basic_Demos-Enroll_Season               2736 non-null   object
 1   Basic_Demos-Age                         2736 non-null   int64
 2   Basic_Demos-Sex                         2736 non-null   int64
 3   CGAS-Season                             2342 non-null   object
 4   CGAS-CGAS_Score                         2342 non-null   float64
 5   Physical-Season                         2595 non-null   object
 6   Physical-BMI                            2527 non-null   float64
 7   Physical-Height                         2530 non-null   float64
 8   Physical-Weight                         2572 non-null   float64
 9   Physical-Diastolic_BP                   2478 non-null   float64
 10  Physical-HeartRate                      2486 non-null   float64
 11  Physical-Systolic_BP                    2478 non-null   float64
 12  Fitness_Endurance-Season                1260 non-null   object
 13  FGC-Season                              2647 non-null   object
 14  FGC-FGC_CU                              1919 non-null   float64
 15  FGC-FGC_CU_Zone                         1884 non-null   float64
 16  FGC-FGC_PU                              1909 non-null   float64
 17  FGC-FGC_PU_Zone                         1875 non-null   float64
 18  FGC-FGC_SRL                             1911 non-null   float64
 19  FGC-FGC_SRL_Zone                        1877 non-null   float64
 20  FGC-FGC_SRR                             1913 non-null   float64
 21  FGC-FGC_SRR_Zone                        1879 non-null   float64
 22  FGC-FGC_TL                              1919 non-null   float64
 23  FGC-FGC_TL_Zone                         1885 non-null   float64
 24  BIA-Season                              1844 non-null   object
 25  BIA-BIA_Activity_Level_num              1813 non-null   float64
 26  BIA-BIA_BMC                             1813 non-null   float64
 27  BIA-BIA_BMI                             1813 non-null   float64
 28  BIA-BIA_BMR                             1813 non-null   float64
 29  BIA-BIA_DEE                             1813 non-null   float64
 30  BIA-BIA_ECW                             1813 non-null   float64
 31  BIA-BIA_FFM                             1813 non-null   float64
 32  BIA-BIA_FFMI                            1813 non-null   float64
 33  BIA-BIA_FMI                             1813 non-null   float64
 34  BIA-BIA_Fat                             1813 non-null   float64
 35  BIA-BIA_Frame_num                       1813 non-null   float64
 36  BIA-BIA_ICW                             1813 non-null   float64
 37  BIA-BIA_LDM                             1813 non-null   float64
 38  BIA-BIA_LST                             1813 non-null   float64
 39  BIA-BIA_SMM                             1813 non-null   float64
 40  BIA-BIA_TBW                             1813 non-null   float64
 41  PAQ_C-Season                            1440 non-null   object
 42  PAQ_C-PAQ_C_Total                       1440 non-null   float64
 43  SDS-Season                              2527 non-null   object
 44  SDS-SDS_Total_Raw                       2527 non-null   float64
 45  SDS-SDS_Total_T                         2525 non-null   float64
 46  PreInt_EduHx-Season                     2719 non-null   object
 47  PreInt_EduHx-computerinternet_hoursday  2654 non-null   float64
dtypes: float64(37), int64(2), object(9)
memory usage: 1.0+ MB

In [26]:
X_train = clash_features(X_train)

Feature: FGC-FGC_CU - Zone: FGC-FGC_CU_Zone
Feature: FGC-FGC_PU - Zone: FGC-FGC_PU_Zone
Feature: FGC-FGC_SRL - Zone: FGC-FGC_SRL_Zone
Feature: FGC-FGC_SRR - Zone: FGC-FGC_SRR_Zone
Feature: FGC-FGC_TL - Zone: FGC-FGC_TL_Zone

In [27]:
X_train.head()

,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,Physical-Diastolic_BP,...,BIA-BIA_LST,BIA-BIA_SMM,BIA-BIA_TBW,PAQ_C-Season,PAQ_C-PAQ_C_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday
0,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,NaN,...,38.9177,19.5413,32.6909,NaN,NaN,NaN,NaN,NaN,Fall,3.0
1,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,75.0,...,39.4497,15.4107,27.0552,Fall,2.340,Fall,46.0,64.0,Summer,0.0
2,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,65.0,...,NaN,NaN,NaN,Summer,2.170,Fall,38.0,54.0,Summer,2.0
3,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,60.0,...,58.9338,26.4798,45.9966,Winter,2.451,Summer,31.0,45.0,Winter,0.0
5,Spring,13,1,Winter,50.0,Summer,22.279952,59.5,112.2,60.0,...,79.6982,35.3804,63.1265,Spring,4.110,Summer,40.0,56.0,Spring,0.0

In [28]:
numerical_features   = X_train.select_dtypes(include=[np.number])
categorical_features = X_train.select_dtypes(exclude=[np.number])

numerical_list   = numerical_features.columns.tolist()
categorical_list = categorical_features.columns.tolist()

In [29]:
decoded_categorical = pd.get_dummies(categorical_features)
decoded_categorical *= 1
decoded_categorical.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2736 entries, 0 to 3958
Data columns (total 36 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Basic_Demos-Enroll_Season_Fall    2736 non-null   int64
 1   Basic_Demos-Enroll_Season_Spring  2736 non-null   int64
 2   Basic_Demos-Enroll_Season_Summer  2736 non-null   int64
 3   Basic_Demos-Enroll_Season_Winter  2736 non-null   int64
 4   CGAS-Season_Fall                  2736 non-null   int64
 5   CGAS-Season_Spring                2736 non-null   int64
 6   CGAS-Season_Summer                2736 non-null   int64
 7   CGAS-Season_Winter                2736 non-null   int64
 8   Physical-Season_Fall              2736 non-null   int64
 9   Physical-Season_Spring            2736 non-null   int64
 10  Physical-Season_Summer            2736 non-null   int64
 11  Physical-Season_Winter            2736 non-null   int64
 12  Fitness_Endurance-Season_Fall     2736 non-null   int64
 13  Fitness_Endurance-Season_Spring   2736 non-null   int64
 14  Fitness_Endurance-Season_Summer   2736 non-null   int64
 15  Fitness_Endurance-Season_Winter   2736 non-null   int64
 16  FGC-Season_Fall                   2736 non-null   int64
 17  FGC-Season_Spring                 2736 non-null   int64
 18  FGC-Season_Summer                 2736 non-null   int64
 19  FGC-Season_Winter                 2736 non-null   int64
 20  BIA-Season_Fall                   2736 non-null   int64
 21  BIA-Season_Spring                 2736 non-null   int64
 22  BIA-Season_Summer                 2736 non-null   int64
 23  BIA-Season_Winter                 2736 non-null   int64
 24  PAQ_C-Season_Fall                 2736 non-null   int64
 25  PAQ_C-Season_Spring               2736 non-null   int64
 26  PAQ_C-Season_Summer               2736 non-null   int64
 27  PAQ_C-Season_Winter               2736 non-null   int64
 28  SDS-Season_Fall                   2736 non-null   int64
 29  SDS-Season_Spring                 2736 non-null   int64
 30  SDS-Season_Summer                 2736 non-null   int64
 31  SDS-Season_Winter                 2736 non-null   int64
 32  PreInt_EduHx-Season_Fall          2736 non-null   int64
 33  PreInt_EduHx-Season_Spring        2736 non-null   int64
 34  PreInt_EduHx-Season_Summer        2736 non-null   int64
 35  PreInt_EduHx-Season_Winter        2736 non-null   int64
dtypes: int64(36)
memory usage: 790.9 KB

In [30]:
X_train_num.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2736 entries, 0 to 3958
Data columns (total 61 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Basic_Demos-Age                         2736 non-null   float64
 1   Basic_Demos-Sex                         2736 non-null   float64
 2   CGAS-CGAS_Score                         2342 non-null   float64
 3   Physical-BMI                            2527 non-null   float64
 4   Physical-Height                         2530 non-null   float64
 5   Physical-Weight                         2572 non-null   float64
 6   Physical-Waist_Circumference            483 non-null    float64
 7   Physical-Diastolic_BP                   2478 non-null   float64
 8   Physical-HeartRate                      2486 non-null   float64
 9   Physical-Systolic_BP                    2478 non-null   float64
 10  FGC-FGC_CU                              1884 non-null   float64
 11  FGC-FGC_GSND                            864 non-null    float64
 12  FGC-FGC_GSD                             864 non-null    float64
 13  FGC-FGC_PU                              1874 non-null   float64
 14  FGC-FGC_SRL                             1877 non-null   float64
 15  FGC-FGC_SRR                             1879 non-null   float64
 16  FGC-FGC_TL                              1885 non-null   float64
 17  BIA-BIA_Activity_Level_num              1813 non-null   float64
 18  BIA-BIA_BMC                             1813 non-null   float64
 19  BIA-BIA_BMI                             1813 non-null   float64
 20  BIA-BIA_BMR                             1813 non-null   float64
 21  BIA-BIA_DEE                             1813 non-null   float64
 22  BIA-BIA_ECW                             1813 non-null   float64
 23  BIA-BIA_FFM                             1813 non-null   float64
 24  BIA-BIA_FFMI                            1813 non-null   float64
 25  BIA-BIA_FMI                             1813 non-null   float64
 26  BIA-BIA_Fat                             1813 non-null   float64
 27  BIA-BIA_Frame_num                       1813 non-null   float64
 28  BIA-BIA_ICW                             1813 non-null   float64
 29  BIA-BIA_LDM                             1813 non-null   float64
 30  BIA-BIA_LST                             1813 non-null   float64
 31  BIA-BIA_SMM                             1813 non-null   float64
 32  BIA-BIA_TBW                             1813 non-null   float64
 33  PAQ_A-PAQ_A_Total                       363 non-null    float64
 34  PAQ_C-PAQ_C_Total                       1440 non-null   float64
 35  PCIAT-PCIAT_01                          2733 non-null   float64
 36  PCIAT-PCIAT_02                          2734 non-null   float64
 37  PCIAT-PCIAT_03                          2731 non-null   float64
 38  PCIAT-PCIAT_04                          2731 non-null   float64
 39  PCIAT-PCIAT_05                          2729 non-null   float64
 40  PCIAT-PCIAT_06                          2732 non-null   float64
 41  PCIAT-PCIAT_07                          2729 non-null   float64
 42  PCIAT-PCIAT_08                          2730 non-null   float64
 43  PCIAT-PCIAT_09                          2730 non-null   float64
 44  PCIAT-PCIAT_10                          2733 non-null   float64
 45  PCIAT-PCIAT_11                          2734 non-null   float64
 46  PCIAT-PCIAT_12                          2731 non-null   float64
 47  PCIAT-PCIAT_13                          2729 non-null   float64
 48  PCIAT-PCIAT_14                          2732 non-null   float64
 49  PCIAT-PCIAT_15                          2730 non-null   float64
 50  PCIAT-PCIAT_16                          2728 non-null   float64
 51  PCIAT-PCIAT_17                          2725 non-null   float64
 52  PCIAT-PCIAT_18                          2728 non-null   float64
 53  PCIAT-PCIAT_19                          2730 non-null   float64
 54  PCIAT-PCIAT_20                          2733 non-null   float64
 55  PCIAT-PCIAT_Total                       2736 non-null   float64
 56  SDS-SDS_Total_Raw                       2527 non-null   float64
 57  SDS-SDS_Total_T                         2525 non-null   float64
 58  PreInt_EduHx-computerinternet_hoursday  2654 non-null   float64
 59  sii                                     2736 non-null   float64
 60  Fitness_Endurance-Time                  727 non-null    float64
dtypes: float64(61)
memory usage: 1.3 MB

In [31]:
X_train_num.head()

,Basic_Demos-Age,Basic_Demos-Sex,CGAS-CGAS_Score,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,Physical-Diastolic_BP,Physical-HeartRate,Physical-Systolic_BP,...,PCIAT-PCIAT_17,PCIAT-PCIAT_18,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-computerinternet_hoursday,sii,Fitness_Endurance-Time
0,5.0,0.0,51.0,16.877316,46.0,50.8,NaN,NaN,NaN,NaN,...,4.0,4.0,2.0,4.0,55.0,NaN,NaN,3.0,2.0,NaN
1,9.0,0.0,NaN,14.035590,48.0,46.0,22.0,75.0,70.0,122.0,...,0.0,0.0,0.0,0.0,0.0,46.0,64.0,0.0,0.0,NaN
2,10.0,1.0,71.0,16.648696,56.5,75.6,NaN,65.0,94.0,117.0,...,2.0,2.0,1.0,1.0,28.0,38.0,54.0,2.0,0.0,458.0
3,9.0,0.0,71.0,18.292347,56.0,81.6,NaN,60.0,97.0,117.0,...,4.0,3.0,4.0,1.0,44.0,31.0,45.0,0.0,1.0,583.0
5,13.0,1.0,50.0,22.279952,59.5,112.2,NaN,60.0,73.0,102.0,...,3.0,1.0,2.0,1.0,34.0,40.0,56.0,0.0,1.0,NaN

In [32]:
pd.options.mode.chained_assignment = None  # default='warn'

# fill the numerical dataset with the mean of the column
def random_imputation(series):
    """
    Fill missing values in a pandas series with random sampling from non-missing values.
    """
    missing_indices = series[series.isnull()].index
    sampled_values = np.random.choice(series.dropna(), size=len(missing_indices), replace=True)
    #i want to align the value at the same type of the series: if it is an int i want to truncate my float mean
    sampled_values = sampled_values.astype(series.dtype)
    series.loc[missing_indices] = sampled_values
    return series

# Apply to a feature
for column in numerical_features.columns:
    if numerical_features[column].isnull().sum() > 0:  # Check if column has missing values
        print(f"Imputing missing values in feature: {column}")
        numerical_features[column] = random_imputation(numerical_features[column])

Imputing missing values in feature: CGAS-CGAS_Score
Imputing missing values in feature: Physical-BMI
Imputing missing values in feature: Physical-Height
Imputing missing values in feature: Physical-Weight
Imputing missing values in feature: Physical-Diastolic_BP
Imputing missing values in feature: Physical-HeartRate
Imputing missing values in feature: Physical-Systolic_BP
Imputing missing values in feature: FGC-FGC_CU
Imputing missing values in feature: FGC-FGC_PU
Imputing missing values in feature: FGC-FGC_SRL
Imputing missing values in feature: FGC-FGC_SRR
Imputing missing values in feature: FGC-FGC_TL
Imputing missing values in feature: BIA-BIA_Activity_Level_num
Imputing missing values in feature: BIA-BIA_BMC
Imputing missing values in feature: BIA-BIA_BMI
Imputing missing values in feature: BIA-BIA_BMR
Imputing missing values in feature: BIA-BIA_DEE
Imputing missing values in feature: BIA-BIA_ECW
Imputing missing values in feature: BIA-BIA_FFM
Imputing missing values in feature: BIA-BIA_FFMI
Imputing missing values in feature: BIA-BIA_FMI
Imputing missing values in feature: BIA-BIA_Fat
Imputing missing values in feature: BIA-BIA_Frame_num
Imputing missing values in feature: BIA-BIA_ICW
Imputing missing values in feature: BIA-BIA_LDM
Imputing missing values in feature: BIA-BIA_LST
Imputing missing values in feature: BIA-BIA_SMM
Imputing missing values in feature: BIA-BIA_TBW
Imputing missing values in feature: PAQ_C-PAQ_C_Total
Imputing missing values in feature: SDS-SDS_Total_Raw
Imputing missing values in feature: SDS-SDS_Total_T
Imputing missing values in feature: PreInt_EduHx-computerinternet_hoursday

In [33]:
numerical_features.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2736 entries, 0 to 3958
Data columns (total 34 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Basic_Demos-Age                         2736 non-null   int64
 1   Basic_Demos-Sex                         2736 non-null   int64
 2   CGAS-CGAS_Score                         2736 non-null   float64
 3   Physical-BMI                            2736 non-null   float64
 4   Physical-Height                         2736 non-null   float64
 5   Physical-Weight                         2736 non-null   float64
 6   Physical-Diastolic_BP                   2736 non-null   float64
 7   Physical-HeartRate                      2736 non-null   float64
 8   Physical-Systolic_BP                    2736 non-null   float64
 9   FGC-FGC_CU                              2736 non-null   float64
 10  FGC-FGC_PU                              2736 non-null   float64
 11  FGC-FGC_SRL                             2736 non-null   float64
 12  FGC-FGC_SRR                             2736 non-null   float64
 13  FGC-FGC_TL                              2736 non-null   float64
 14  BIA-BIA_Activity_Level_num              2736 non-null   float64
 15  BIA-BIA_BMC                             2736 non-null   float64
 16  BIA-BIA_BMI                             2736 non-null   float64
 17  BIA-BIA_BMR                             2736 non-null   float64
 18  BIA-BIA_DEE                             2736 non-null   float64
 19  BIA-BIA_ECW                             2736 non-null   float64
 20  BIA-BIA_FFM                             2736 non-null   float64
 21  BIA-BIA_FFMI                            2736 non-null   float64
 22  BIA-BIA_FMI                             2736 non-null   float64
 23  BIA-BIA_Fat                             2736 non-null   float64
 24  BIA-BIA_Frame_num                       2736 non-null   float64
 25  BIA-BIA_ICW                             2736 non-null   float64
 26  BIA-BIA_LDM                             2736 non-null   float64
 27  BIA-BIA_LST                             2736 non-null   float64
 28  BIA-BIA_SMM                             2736 non-null   float64
 29  BIA-BIA_TBW                             2736 non-null   float64
 30  PAQ_C-PAQ_C_Total                       2736 non-null   float64
 31  SDS-SDS_Total_Raw                       2736 non-null   float64
 32  SDS-SDS_Total_T                         2736 non-null   float64
 33  PreInt_EduHx-computerinternet_hoursday  2736 non-null   float64
dtypes: float64(32), int64(2)
memory usage: 812.7 KB

In [34]:
numerical_features.head()

,Basic_Demos-Age,Basic_Demos-Sex,CGAS-CGAS_Score,Physical-BMI,Physical-Height,Physical-Weight,Physical-Diastolic_BP,Physical-HeartRate,Physical-Systolic_BP,FGC-FGC_CU,...,BIA-BIA_Frame_num,BIA-BIA_ICW,BIA-BIA_LDM,BIA-BIA_LST,BIA-BIA_SMM,BIA-BIA_TBW,PAQ_C-PAQ_C_Total,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-computerinternet_hoursday
0,5,0,51.0,16.877316,46.0,50.8,111.0,83.0,100.0,0.0,...,1.0,24.4349,8.89536,38.9177,19.5413,32.6909,3.300,37.0,50.0,3.0
1,9,0,50.0,14.035590,48.0,46.0,75.0,70.0,122.0,3.0,...,1.0,21.0352,14.97400,39.4497,15.4107,27.0552,2.340,46.0,64.0,0.0
2,10,1,71.0,16.648696,56.5,75.6,65.0,94.0,117.0,20.1,...,2.0,47.0740,14.02140,98.8850,38.1995,46.3166,2.170,38.0,54.0,2.0
3,9,0,71.0,18.292347,56.0,81.6,60.0,97.0,117.0,18.1,...,2.0,30.4041,16.77900,58.9338,26.4798,45.9966,2.451,31.0,45.0,0.0
5,13,1,50.0,22.279952,59.5,112.2,60.0,73.0,102.0,12.0,...,2.0,32.9141,20.90200,79.6982,35.3804,63.1265,4.110,40.0,56.0,0.0